### ISSUE TITLE
Update 1.1 broke this mod

### ISSUE THREAD

**Issue by kaoeamorim** [AaronCRobinson/NamesGalore#4]
Hi! 

First of all, I thank you for your work on this mod. It's honestly one of the most amazing ones. Adds so much flavor.

I'd like to ask if there is any possibility of you updating this mod.

Sadly it seems that when I add it to the list after 1.1 it raises some red and yellow errors. Strangely, adding NamesGalore breaks some other mods, like Common Sense, Color Mood Bar, RimHUD, and Smart Medicine (and some others).

It doesn't matter if i load NamesGalore before all other mods, or after.

It could maybe be related to the recent Harmony update.

Here are the logs loading last:
https://gist.github.com/0b3bd113f1717dfe2d156ebcd4f611fc

Here are the logs loading after Harmony and HugsLib:
https://gist.github.com/7189336d0b2950ce1c47ed1dfd751811

I don't know if that helps.

Thank you very much in advance!

**Comment by AaronCRobinson** [comment]
The new release should be ready. Let me know if you experience any issues and I will leave the issue open until I hear back.

https://github.com/AaronCRobinson/NamesGalore/releases/tag/v1.1.0

**Comment by kaoeamorim** [comment]
Hi! The mod is perfect now. Tested for quite a while and no issues whatsoever. Thank you very much!

You should probably announce that on the discord channel or something, since the mod isn't on the workshop, so people know it's updated.

Again, thank you!

**Comment by AaronCRobinson** [comment]
Hey.

It would be great to announce on the discord channel but I am in China and it's blocked. I don't use a VPN or have another work-around to this yet but might try to find a solution soon. You are welcome to post the info on my behalf. 

The preview image is under the about:

https://github.com/AaronCRobinson/NamesGalore/blob/master/About/preview.png

Likewise, aside from dealing with the community on the workshop, I cannot post there either because of China's internet. You are likewise welcome to share there and funnel any issues or details to me from Steam Community.

I am glad you enjoy the mod.

Cheers.

**Comment by kaoeamorim** [comment]
Amazing! And thank you so much. I'll be sure to help sharing the mod with the community.

**Comment by kaoeamorim** [comment]
Hey

Just published the mod on the Workshop. If you'd like me to change anything, please let me know.

Here's the link: https://steamcommunity.com/sharedfiles/filedetails/?id=2017130910

**Comment by AaronCRobinson** [comment]
I added issue templates to this repository to better support one of the questions from the community you received. There are now issue types for: "Bug report", "Feature request", and "Name data". A user wishing to add new name data needs to provide the files "First_Female.txt", "First_Male.txt",  "Last.txt",  "Nick_Female.txt", "Nick_Male.txt", and "Nick_Unisex.txt". I will try to add a Wiki to better describe this process and will update the Readme briefly now. 

To answer Klaus' question, no need to mod the assembly. You can update the raw files and they are injected at each runtime, as long as it's the appropriate language as the users or the "international flag" is set in the settings. The only reason to upload those files as a "Name data" issue is if the user wants to share their hardwork with the community. 

Thanks again. I am closing this issue out.
